# Generated by Django 3.1.3 on 2020-11-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_auto_20201115_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Warden_ID',
            new_name='Warden_id',
        ),
    ]
